package codenest.hibernatets4.model;
// Generated 2019-1-28 10:59:08 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * BoUniconfigType generated by hbm2java
 */
public class BoUniconfigType implements java.io.Serializable {

	private int classid;
	private int productid;
	private String uniconfigname;
	private String uniconfigkey;
	private Set boUniconfigKeywordInfos = new HashSet(0);

	public BoUniconfigType() {
	}

	public BoUniconfigType(int classid, int productid, String uniconfigname, String uniconfigkey) {
		this.classid = classid;
		this.productid = productid;
		this.uniconfigname = uniconfigname;
		this.uniconfigkey = uniconfigkey;
	}

	public BoUniconfigType(int classid, int productid, String uniconfigname, String uniconfigkey,
			Set boUniconfigKeywordInfos) {
		this.classid = classid;
		this.productid = productid;
		this.uniconfigname = uniconfigname;
		this.uniconfigkey = uniconfigkey;
		this.boUniconfigKeywordInfos = boUniconfigKeywordInfos;
	}

	public int getClassid() {
		return this.classid;
	}

	public void setClassid(int classid) {
		this.classid = classid;
	}

	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	public String getUniconfigname() {
		return this.uniconfigname;
	}

	public void setUniconfigname(String uniconfigname) {
		this.uniconfigname = uniconfigname;
	}

	public String getUniconfigkey() {
		return this.uniconfigkey;
	}

	public void setUniconfigkey(String uniconfigkey) {
		this.uniconfigkey = uniconfigkey;
	}

	public Set getBoUniconfigKeywordInfos() {
		return this.boUniconfigKeywordInfos;
	}

	public void setBoUniconfigKeywordInfos(Set boUniconfigKeywordInfos) {
		this.boUniconfigKeywordInfos = boUniconfigKeywordInfos;
	}

}
