package codenest.hibernatets4.model;
// Generated 2019-1-28 10:59:08 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * BoUniconfigInfo generated by hbm2java
 */
public class BoUniconfigInfo implements java.io.Serializable {

	private int id;
	private Integer version;
	private int classid;
	private String ext;
	private Date logtime;
	private Date modifytime;

	public BoUniconfigInfo() {
	}

	public BoUniconfigInfo(int id, int classid) {
		this.id = id;
		this.classid = classid;
	}

	public BoUniconfigInfo(int id, int classid, String ext, Date logtime, Date modifytime) {
		this.id = id;
		this.classid = classid;
		this.ext = ext;
		this.logtime = logtime;
		this.modifytime = modifytime;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public int getClassid() {
		return this.classid;
	}

	public void setClassid(int classid) {
		this.classid = classid;
	}

	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	public Date getLogtime() {
		return this.logtime;
	}

	public void setLogtime(Date logtime) {
		this.logtime = logtime;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

}
