package codenest.hibernatets4.model;
// Generated 2019-1-28 10:59:08 by Hibernate Tools 5.3.0.Beta2

/**
 * BoUniconfigKeywordIvindex generated by hbm2java
 */
public class BoUniconfigKeywordIvindex implements java.io.Serializable {

	private BoUniconfigKeywordIvindexId id;

	public BoUniconfigKeywordIvindex() {
	}

	public BoUniconfigKeywordIvindex(BoUniconfigKeywordIvindexId id) {
		this.id = id;
	}

	public BoUniconfigKeywordIvindexId getId() {
		return this.id;
	}

	public void setId(BoUniconfigKeywordIvindexId id) {
		this.id = id;
	}

}
