package codenest.hibernatets4.model;
// Generated 2019-1-28 10:59:08 by Hibernate Tools 5.3.0.Beta2

/**
 * BoUniconfigMap generated by hbm2java
 */
public class BoUniconfigMap implements java.io.Serializable {

	private BoUniconfigMapId id;
	private int keyid;

	public BoUniconfigMap() {
	}

	public BoUniconfigMap(BoUniconfigMapId id, int keyid) {
		this.id = id;
		this.keyid = keyid;
	}

	public BoUniconfigMapId getId() {
		return this.id;
	}

	public void setId(BoUniconfigMapId id) {
		this.id = id;
	}

	public int getKeyid() {
		return this.keyid;
	}

	public void setKeyid(int keyid) {
		this.keyid = keyid;
	}

}
