package codenest.hibernatets4.model;
// Generated 2019-1-28 10:59:08 by Hibernate Tools 5.3.0.Beta2

/**
 * BoUniconfigKeywordEnumId generated by hbm2java
 */
public class BoUniconfigKeywordEnumId implements java.io.Serializable {

	private int keywordid;
	private int enum_;
	private String show;

	public BoUniconfigKeywordEnumId() {
	}

	public BoUniconfigKeywordEnumId(int keywordid, int enum_) {
		this.keywordid = keywordid;
		this.enum_ = enum_;
	}

	public BoUniconfigKeywordEnumId(int keywordid, int enum_, String show) {
		this.keywordid = keywordid;
		this.enum_ = enum_;
		this.show = show;
	}

	public int getKeywordid() {
		return this.keywordid;
	}

	public void setKeywordid(int keywordid) {
		this.keywordid = keywordid;
	}

	public int getEnum_() {
		return this.enum_;
	}

	public void setEnum_(int enum_) {
		this.enum_ = enum_;
	}

	public String getShow() {
		return this.show;
	}

	public void setShow(String show) {
		this.show = show;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BoUniconfigKeywordEnumId))
			return false;
		BoUniconfigKeywordEnumId castOther = (BoUniconfigKeywordEnumId) other;

		return (this.getKeywordid() == castOther.getKeywordid()) && (this.getEnum_() == castOther.getEnum_())
				&& ((this.getShow() == castOther.getShow()) || (this.getShow() != null && castOther.getShow() != null
						&& this.getShow().equals(castOther.getShow())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getKeywordid();
		result = 37 * result + this.getEnum_();
		result = 37 * result + (getShow() == null ? 0 : this.getShow().hashCode());
		return result;
	}

}
