package codenest.hibernatets4.model;
// Generated 2019-1-28 10:59:08 by Hibernate Tools 5.3.0.Beta2

/**
 * BoUniconfigKeywordIvindexId generated by hbm2java
 */
public class BoUniconfigKeywordIvindexId implements java.io.Serializable {

	private Integer productid;
	private Integer keywordid;
	private String location;

	public BoUniconfigKeywordIvindexId() {
	}

	public BoUniconfigKeywordIvindexId(Integer productid, Integer keywordid, String location) {
		this.productid = productid;
		this.keywordid = keywordid;
		this.location = location;
	}

	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	public Integer getKeywordid() {
		return this.keywordid;
	}

	public void setKeywordid(Integer keywordid) {
		this.keywordid = keywordid;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BoUniconfigKeywordIvindexId))
			return false;
		BoUniconfigKeywordIvindexId castOther = (BoUniconfigKeywordIvindexId) other;

		return ((this.getProductid() == castOther.getProductid()) || (this.getProductid() != null
				&& castOther.getProductid() != null && this.getProductid().equals(castOther.getProductid())))
				&& ((this.getKeywordid() == castOther.getKeywordid()) || (this.getKeywordid() != null
						&& castOther.getKeywordid() != null && this.getKeywordid().equals(castOther.getKeywordid())))
				&& ((this.getLocation() == castOther.getLocation()) || (this.getLocation() != null
						&& castOther.getLocation() != null && this.getLocation().equals(castOther.getLocation())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductid() == null ? 0 : this.getProductid().hashCode());
		result = 37 * result + (getKeywordid() == null ? 0 : this.getKeywordid().hashCode());
		result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
		return result;
	}

}
