package codenest.hibernatets4.model;
// Generated 2019-1-28 10:59:08 by Hibernate Tools 5.3.0.Beta2

/**
 * BoUniconfigMapId generated by hbm2java
 */
public class BoUniconfigMapId implements java.io.Serializable {

	private int nodetype;
	private int nodeid;

	public BoUniconfigMapId() {
	}

	public BoUniconfigMapId(int nodetype, int nodeid) {
		this.nodetype = nodetype;
		this.nodeid = nodeid;
	}

	public int getNodetype() {
		return this.nodetype;
	}

	public void setNodetype(int nodetype) {
		this.nodetype = nodetype;
	}

	public int getNodeid() {
		return this.nodeid;
	}

	public void setNodeid(int nodeid) {
		this.nodeid = nodeid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BoUniconfigMapId))
			return false;
		BoUniconfigMapId castOther = (BoUniconfigMapId) other;

		return (this.getNodetype() == castOther.getNodetype()) && (this.getNodeid() == castOther.getNodeid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNodetype();
		result = 37 * result + this.getNodeid();
		return result;
	}

}
