package codenest.hibernatets4.model;
// Generated 2019-1-28 10:59:08 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * BoUniconfigKeywordInfo generated by hbm2java
 */
public class BoUniconfigKeywordInfo implements java.io.Serializable {

	private int keywordid;
	private BoUniconfigType boUniconfigType;
	private String keyword;
	private String show;
	private String type;
	private Set boUniconfigKeywordEnums = new HashSet(0);

	public BoUniconfigKeywordInfo() {
	}

	public BoUniconfigKeywordInfo(int keywordid, BoUniconfigType boUniconfigType, String keyword, String show) {
		this.keywordid = keywordid;
		this.boUniconfigType = boUniconfigType;
		this.keyword = keyword;
		this.show = show;
	}

	public BoUniconfigKeywordInfo(int keywordid, BoUniconfigType boUniconfigType, String keyword, String show,
			String type, Set boUniconfigKeywordEnums) {
		this.keywordid = keywordid;
		this.boUniconfigType = boUniconfigType;
		this.keyword = keyword;
		this.show = show;
		this.type = type;
		this.boUniconfigKeywordEnums = boUniconfigKeywordEnums;
	}

	public int getKeywordid() {
		return this.keywordid;
	}

	public void setKeywordid(int keywordid) {
		this.keywordid = keywordid;
	}

	public BoUniconfigType getBoUniconfigType() {
		return this.boUniconfigType;
	}

	public void setBoUniconfigType(BoUniconfigType boUniconfigType) {
		this.boUniconfigType = boUniconfigType;
	}

	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	public String getShow() {
		return this.show;
	}

	public void setShow(String show) {
		this.show = show;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getBoUniconfigKeywordEnums() {
		return this.boUniconfigKeywordEnums;
	}

	public void setBoUniconfigKeywordEnums(Set boUniconfigKeywordEnums) {
		this.boUniconfigKeywordEnums = boUniconfigKeywordEnums;
	}

}
