package codenest.hibernate5.domain;
// default package
// Generated 2019-1-28 15:55:01 by Hibernate Tools 5.3.0.Beta2

/**
 * Myorder generated by hbm2java
 */
public class Myorder implements java.io.Serializable {

	private int id;
	private Customer customer;
	private String ordernum;
	private Double money;

	public Myorder() {
	}

	public Myorder(int id, String ordernum) {
		this.id = id;
		this.ordernum = ordernum;
	}

	public Myorder(int id, Customer customer, String ordernum, Double money) {
		this.id = id;
		this.customer = customer;
		this.ordernum = ordernum;
		this.money = money;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getOrdernum() {
		return this.ordernum;
	}

	public void setOrdernum(String ordernum) {
		this.ordernum = ordernum;
	}

	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

}
