package codenest.hiternate6.domain;

import java.util.HashSet;
import java.util.Set;

// Generated 2019-1-29 9:04:49 by Hibernate Tools 5.3.0.Beta2



/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private Set students=new HashSet(0);

    public Teacher() {
    }

	
    public Teacher(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Teacher(int id, String name, String email) {
       this.id = id;
       this.name = name;
       this.email = email;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


	public Set getStudents() {
		return students;
	}


	public void setStudents(Set students) {
		this.students = students;
	}




}


